name = "movie-online"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "movie-online"
database_id = "adb41511-e946-44d5-875c-074c02a661a9"
migrations_dir = "drizzle/migrations"
